extends Node

enum UNIT_TYPE{GROUND,WINGS,SEA}
enum UNIT_MOVEMENT{NONE,FEET,WHEELED,TRACKED,WINGS,RUDDER,SHALLOWWATER,DEEPWATER}
var UNIT_MOVEMENT_DATA = {
	UNIT_MOVEMENT.NONE : {
		"name" : "none",
		"description" : "none",
		"sprite" : load("res://sprites/MovementNone.png"),
	},
	UNIT_MOVEMENT.FEET : {
		"name" : "feet",
		"description" : "feet",
		"sprite" : load("res://sprites/MovementFeet.png"),
	},
	UNIT_MOVEMENT.WHEELED : {
		"name" : "wheeled",
		"description" : "wheeled",
		"sprite" : load("res://sprites/MovementWheeled.png"),
	},
	UNIT_MOVEMENT.TRACKED : {
		"name" : "tracked",
		"description" : "tracked",
		"sprite" : load("res://sprites/MovementTracked.png"),
	},
	UNIT_MOVEMENT.WINGS : {
		"name" : "wings",
		"description" : "wings",
		"sprite" : load("res://sprites/MovementWings.png"),
	},
	UNIT_MOVEMENT.RUDDER : {
		"name" : "rudder",
		"description" : "rudder",
		"sprite" : load("res://sprites/MovementRudder.png"),
	},
	UNIT_MOVEMENT.SHALLOWWATER : {
		"name" : "shallowwater",
		"description" : "shallowwater",
		"sprite" : load("res://sprites/MovementRudder.png"),
	},
	UNIT_MOVEMENT.DEEPWATER : {
		"name" : "deepwater",
		"description" : "deepwater",
		"sprite" : load("res://sprites/MovementRudder.png"),
	},
}

enum UNIT_ARMOR{HEAVY,MEDIUM,LIGHT}
var UNIT_ARMOR_DATA = {
	UNIT_ARMOR.HEAVY : {
		"name" : "heavy",
		"description" : "heavy",
		"sprite" : load("res://sprites/ArmorHeavy.png"),
	},
	UNIT_ARMOR.MEDIUM : {
		"name" : "medium",
		"description" : "medium",
		"sprite" : load("res://sprites/ArmorMedium.png"),
	},
	UNIT_ARMOR.LIGHT : {
		"name" : "light",
		"description" : "light",
		"sprite" : load("res://sprites/ArmorLight.png"),
	},
}

enum UNIT_WEAPON{HEAVY,MEDIUM,LIGHT,NONE}
var UNIT_WEAPON_DATA = {
	UNIT_WEAPON.HEAVY : {
		"name" : "heavy",
		"description" : "heavy",
		"sprite" : load("res://sprites/WeaponHeavy.png"),
	},
	UNIT_WEAPON.MEDIUM : {
		"name" : "medium",
		"description" : "medium",
		"sprite" : load("res://sprites/WeaponMedium.png"),
	},
	UNIT_WEAPON.LIGHT : {
		"name" : "light",
		"description" : "light",
		"sprite" : load("res://sprites/WeaponLight.png"),
	},
	UNIT_WEAPON.NONE : {
		"name" : "none",
		"description" : "none",
		"sprite" : load("res://sprites/weapon_none.png"),
	},
}

enum UNIT_TRAIT{
	SKYSWEEPER,COUNTERBATTERY,CAPTURE,FLAK,TRANSPORT,UNBUILDABLE,CLOAKING,
	AIRBOUND,SEABOUND,GROUNDBOUND,BLITZ,MAMMOTH,
	MAINTENANCE,FIREBOMB,OVERDRIVE,RADAR,ANTISUB,SUBMERGED,MASSIVEHULL,
	CLOAKDAMAGE,TRACKING,CONSTRUCTOR,EXTRACTOR,IRREPARABLE,
	JAMMING,PIERCING,FIXED,LINCHPIN,NOTSELECTABLE,BLINDSPOT,STUN,SCAVENGE,
	COURAGEUNDERFIRE,
}
var UNIT_TRAIT_DATA = {
	UNIT_TRAIT.SKYSWEEPER : {
		"name" : "Skysweeper",
		"description" : "This unit can engage air craft.",
		"sprite" : load("res://sprites/unittrait/Skysweeper.png"),
		"visible" : true
	},
	UNIT_TRAIT.BLINDSPOT : {
		"name" : "Blind Spot",
		"description" : "This unit cannot counter attack.",
		"sprite" : load("res://sprites/unittrait/BlindSpot.png"),
		"visible" : true
	},
	UNIT_TRAIT.LINCHPIN : {
		"name" : "Linchpin",
		"description" : "Keep at least one Linchpin unit alive to stay in the fight.",
		"sprite" : load("res://sprites/unittrait/Linchpin.png"),
		"visible" : true
	},
	UNIT_TRAIT.SCAVENGE : {
		"name" : "Scavenge",
		"description" : "Unit can move and attack again if it kills its target.",
		"sprite" : load("res://sprites/unittrait/Scavenge.png"),
		"visible" : true
	},
	UNIT_TRAIT.COUNTERBATTERY : {
		"name" : "CounterBattery",
		"description" : "Counter-attacks ranged units.",
		"sprite" : load("res://sprites/unittrait/CounterBattery.png"),
		"visible" : true
	},
	UNIT_TRAIT.NOTSELECTABLE : {
		"name" : "NotSelectable",
		"description" : "This unit isn't selectable. It just sits there.",
		"sprite" : load("res://sprites/unittrait/NotSelectable.png"),
		"visible" : true
	},
	UNIT_TRAIT.PIERCING : {
		"name" : "Piercing",
		"description" : "Attack damages any unit directly behind target.",
		"sprite" : load("res://sprites/unittrait/Piercing.png"),
		"visible" : true
	},
	UNIT_TRAIT.FIXED : {
		"name" : "Fixed",
		"description" : "This unit does not prevent military defeat.",
		"sprite" : load("res://sprites/unittrait/Fixed.png"),
		"visible" : true
	},
	UNIT_TRAIT.JAMMING : {
		"name" : "Jamming",
		"description" : "Emits a no-fly zone that also uncloaks stealth units.",
		"sprite" : load("res://sprites/unittrait/Jamming.png"),
		"visible" : true
	},
	UNIT_TRAIT.IRREPARABLE : {
		"name" : "Irreparable",
		"description" : "This unit cannot be repaired.",
		"sprite" : load("res://sprites/unittrait/Irreparable.png"),
		"visible" : true
	},
	UNIT_TRAIT.EXTRACTOR : {
		"name" : "Extractor",
		"description" : "This unit can extract resources from Ore Deposits.",
		"sprite" : load("res://sprites/unittrait/Extractor.png"),
		"visible" : true
	},
	UNIT_TRAIT.CONSTRUCTOR : {
		"name" : "Constructor",
		"description" : "This unit can build other units.",
		"sprite" : load("res://sprites/unittrait/Constructor.png"),
		"visible" : true
	},
	UNIT_TRAIT.CAPTURE : {
		"name" : "Capture",
		"description" : "This unit can capture properties.",
		"sprite" : load("res://sprites/unittrait/Capture.png"),
		"visible" : true
	},
	UNIT_TRAIT.FLAK : {
		"name" : "Flak",
		"description" : "Does 2x damage to light armor.",
		"sprite" : load("res://sprites/unittrait/Flak.png"),
		"visible" : true
	},
	UNIT_TRAIT.TRANSPORT : {
		"name" : "Transport",
		"description" : "Transports other units.",
		"sprite" : load("res://sprites/unittrait/Transport.png"),
		"visible" : true
	},
	UNIT_TRAIT.UNBUILDABLE : {
		"name" : "Unbuildable",
		"description" : "Cannot be built.",
		"sprite" : load("res://sprites/unittrait/Unbuildable.png"),
		"visible" : true
	},
	UNIT_TRAIT.CLOAKING : {
		"name" : "Cloaking",
		"description" : "This unit cloaks after moving.",
		"sprite" : load("res://sprites/unittrait/Cloaking.png"),
		"visible" : true
	},
	UNIT_TRAIT.CLOAKDAMAGE : {
		"name" : "CloakDamage",
		"description" : "This unit does 2x damage because it is cloaked.",
		"sprite" : load("res://sprites/unittrait/CloakDamage.png"),
		"visible" : true
	},
	UNIT_TRAIT.AIRBOUND : {
		"name" : "AirBound",
		"description" : "This unit can engage air units.",
		"sprite" : load("res://sprites/unittrait/AirBound.png"),
		"visible" : true
	},
	UNIT_TRAIT.SEABOUND : {
		"name" : "SeaBound",
		"description" : "This unit can engage sea units.",
		"sprite" : load("res://sprites/unittrait/SeaBound.png"),
		"visible" : true
	},
	UNIT_TRAIT.GROUNDBOUND : {
		"name" : "GroundBound",
		"description" : "This unit can engage ground units.",
		"sprite" : load("res://sprites/unittrait/GroundBound.png"),
		"visible" : true
	},
	UNIT_TRAIT.BLITZ : {
		"name" : "Blitz",
		"description" : "+20% damage if unit initiates attack.",
		"sprite" : load("res://sprites/unittrait/Blitz.png"),
		"visible" : true
	},
	UNIT_TRAIT.MAMMOTH : {
		"name" : "Mammoth",
		"description" : "Unit does 15% less damage on counter attack.",
		"sprite" : load("res://sprites/unittrait/Mammoth.png"),
		"visible" : true
	},
	#UNIT_TRAIT.COURAGEUNDERFIRE : {
		#"name" : "CourageUnderFire",
		#"description" : "+25% damage on counter attack.",
		#"sprite" : load(),
		#"visible" : true
	#},
	UNIT_TRAIT.MAINTENANCE : {
		"name" : "Maintenance",
		"description" : "Unit heals 5 HP each round.",
		"sprite" : load("res://sprites/unittrait/Maintenance.png"),
		"visible" : true
	},
	UNIT_TRAIT.FIREBOMB : {
		"name" : "FireBomb",
		"description" : "Does 20% more damage if target is on a structure.",
		"sprite" : load("res://sprites/unittrait/FireBomb.png"),
		"visible" : true
	},
	UNIT_TRAIT.OVERDRIVE : {
		"name" : "Overdrive",
		"description" : "+2 range when at full health.",
		"sprite" : load("res://sprites/unittrait/Overdrive.png"),
		"visible" : true
	},
	UNIT_TRAIT.RADAR : {
		"name" : "Radar",
		"description" : "Detects stealth units at the start of its turn.",
		"sprite" : load("res://sprites/unittrait/Radar.png"),
		"visible" : true
	},
	UNIT_TRAIT.ANTISUB : {
		"name" : "AntiSub",
		"description" : "Can attack submerged units.",
		"sprite" : load("res://sprites/unittrait/AntiSub.png"),
		"visible" : true
	},
	UNIT_TRAIT.SUBMERGED : {
		"name" : "Submerged",
		"description" : "Can only be attacked by Anti-Sub units.",
		"sprite" : load("res://sprites/unittrait/Submerged.png"),
		"visible" : true
	},
	UNIT_TRAIT.MASSIVEHULL : {
		"name" : "MassiveHull",
		"description" : "Unit cannot enter shallow waters.",
		"sprite" : load("res://sprites/unittrait/MassiveHull.png"),
		"visible" : true
	},
	UNIT_TRAIT.TRACKING : {
		"name" : "Tracking",
		"description" : "Unit will attack stealth units on interception.",
		"sprite" : load("res://sprites/unittrait/Tracking.png"),
		"visible" : true
	},
	UNIT_TRAIT.STUN : {
		"name" : "Stun",
		"description" : "Enemy units will not counter-attack in response to an attack.",
		"sprite" : load("res://sprites/unittrait/Stun.png"),
		"visible" : true
	},
}

enum TERRAIN_TRAIT{
	GROUND,WATER,IMPASSABLE,UNEVEN,PAVEMENT,RUGGED,PRECIPITOUS,BARBED,SHALLOW,COVER,
	CAMOUFLAGE,BUNKER,HIGHGROUND,FARSIGHT,GARRISON,STRAIT,REDUCEDMOBILITY,HAZARD,CANOPY,SHIELDED,
	CONSTRUCTION,CAPTURABLE,AIRPROFICIENCY,GROUNDPROFICIENCY,SEAPROFICIENCY,LEVEL1OILREFINING,
	LEVEL2OILREFINING,LEVEL3OILREFINING,MISSIONCRITICAL,SHORE,TRICKYWATERS,EXTRACTABLE,
	}
var TERRAIN_TRAIT_DATA = {
	TERRAIN_TRAIT.EXTRACTABLE : {
		"name" : "Extractable",
		"description" : "Resources can be extracted from this tile.",
		"sprite" : load("res://sprites/terraintrait/Extractable.png"),
		"visible" : true,
	},
	TERRAIN_TRAIT.GROUND : {
		"name" : "Ground",
		"description" : "Sea units cannot enter.",
		"sprite" : load("res://sprites/terraintrait/Ground.png"),
		"visible" : true,
	},
	TERRAIN_TRAIT.WATER : {
		"name" : "Water",
		"description" : "Ground units cannot enter.",
		"sprite" : load("res://sprites/terraintrait/Water.png"),
		"visible" : true,
	},
	TERRAIN_TRAIT.IMPASSABLE : {
		"name" : "Impassable",
		"description" : "No unit may enter.",
		"sprite" : load("res://sprites/terraintrait/Impassable.png"),
		"visible" : true,
	},
	TERRAIN_TRAIT.UNEVEN : {
		"name" : "Uneven",
		"description" : "Slows wheeled vehicles.",
		"sprite" : load("res://sprites/terraintrait/Uneven.png"),
		"visible" : true,
	},
	TERRAIN_TRAIT.PAVEMENT : {
		"name" : "Pavement",
		"description" : "no description",
		"sprite" : load("res://sprites/terraintrait/Pavement.png"),
		"visible" : true,
	},
	TERRAIN_TRAIT.RUGGED : {
		"name" : "Rugged",
		"description" : "Slows wheeled vehicles and somewhat slows tracked vehicles.",
		"sprite" : load("res://sprites/terraintrait/Rugged.png"),
		"visible" : true,
	},
	TERRAIN_TRAIT.PRECIPITOUS : {
		"name" : "Precipitous",
		"description" : "Allows only commandos. Severe movement cost.",
		"sprite" : load("res://sprites/terraintrait/Precipitous.png"),
		"visible" : true,
	},
	TERRAIN_TRAIT.BARBED : {
		"name" : "Barbed",
		"description" : "Commandos cannot enter barbed tiles.",
		"sprite" : load("res://sprites/terraintrait/Barbed.png"),
		"visible" : true,
	},
	TERRAIN_TRAIT.SHALLOW : {
		"name" : "Shallow",
		"description" : "Large hulled ships cannot enter shallow waters.",
		"sprite" : load("res://sprites/terraintrait/Shallow.png"),
		"visible" : true,
	},
	TERRAIN_TRAIT.COVER : {
		"name" : "Cover",
		"description" : "Damage to non-air units reduced by 10%.",
		"sprite" : load("res://sprites/terraintrait/Cover.png"),
		"visible" : true,
	},
	TERRAIN_TRAIT.CAMOUFLAGE : {
		"name" : "Camouflage",
		"description" : "Damage to ground and sea units reduced by 20%.",
		"sprite" : load("res://sprites/terraintrait/Camouflage.png"),
		"visible" : true,
	},
	TERRAIN_TRAIT.BUNKER : {
		"name" : "Bunker",
		"description" : "Damage to ground units reduced by 40%.",
		"sprite" : load("res://sprites/terraintrait/Bunker.png"),
		"visible" : true,
	},
	TERRAIN_TRAIT.HIGHGROUND : {
		"name" : "HighGround",
		"description" : "Reduces damage received by ranged fire by 25%",
		"sprite" : load("res://sprites/terraintrait/HighGround.png"),
		"visible" : true,
	},
	TERRAIN_TRAIT.FARSIGHT : {
		"name" : "Farsight",
		"description" : "Increases maximum attack range of ranged units by 1.",
		"sprite" : load("res://sprites/terraintrait/Farsight.png"),
		"visible" : true,
	},
	TERRAIN_TRAIT.GARRISON : {
		"name" : "Garrison",
		"description" : "Damage to non-air units reduced by 50%",
		"sprite" : load("res://sprites/terraintrait/Garrison.png"),
		"visible" : true,
	},
	TERRAIN_TRAIT.STRAIT : {
		"name" : "Strait",
		"description" : "Damage received by sea units is increased by 10%",
		"sprite" : load("res://sprites/terraintrait/Strait.png"),
		"visible" : true,
	},
	TERRAIN_TRAIT.REDUCEDMOBILITY : {
		"name" : "ReducedMobility",
		"description" : "Ship movement is reduced.",
		"sprite" : load("res://sprites/terraintrait/ReducedMobility.png"),
		"visible" : true,
	},
	TERRAIN_TRAIT.TRICKYWATERS : {
		"name" : "TrickyWaters",
		"description" : "Tricky waters severely slow Massive Hull ships and slows all other types.",
		"sprite" : load("res://sprites/terraintrait/TrickyWaters.png"),
		"visible" : true,
	},
	TERRAIN_TRAIT.HAZARD : {
		"name" : "Hazard",
		"description" : "Does 20 damage to any non-air units that start their turn on this tile.",
		"sprite" : load("res://sprites/terraintrait/Hazard.png"),
		"visible" : true,
	},
	TERRAIN_TRAIT.CANOPY : {
		"name" : "Canopy",
		"description" : "Ranged units cannot fire from this tile.",
		"sprite" : load("res://sprites/terraintrait/Canopy.png"),
		"visible" : true,
	},
	TERRAIN_TRAIT.SHIELDED : {
		"name" : "Shielded",
		"description" : "Units in Shielded terrain can't be targetted by ranged units.",
		"sprite" : load("res://sprites/terraintrait/Shielded.png"),
		"visible" : true,
	},
	TERRAIN_TRAIT.CONSTRUCTION : {
		"name" : "Construction",
		"description" : "Controlling team may build new units from this structure.",
		"sprite" : load("res://sprites/terraintrait/Construction.png"),
		"visible" : true,
	},
	TERRAIN_TRAIT.CAPTURABLE : {
		"name" : "Capturable",
		"description" : "This structure can be captured.",
		"sprite" : load("res://sprites/terraintrait/Capturable.png"),
		"visible" : true,
	},
	TERRAIN_TRAIT.AIRPROFICIENCY : {
		"name" : "AirProficiency",
		"description" : "Each Air Control reduces cost of deploying air units by 5%.",
		"sprite" : load("res://sprites/terraintrait/AirProficiency.png"),
		"visible" : true,
	},
	TERRAIN_TRAIT.GROUNDPROFICIENCY : {
		"name" : "GroundProficiency",
		"description" : "Each Ground Control reduces cost of deploying ground units by 5%.",
		"sprite" : load("res://sprites/terraintrait/GroundProficiency.png"),
		"visible" : true,
	},
	TERRAIN_TRAIT.SEAPROFICIENCY : {
		"name" : "SeaProficiency",
		"description" : "Each Sea Control reduces cost of deploying sea units by 5%.",
		"sprite" : load("res://sprites/terraintrait/SeaProficiency.png"),
		"visible" : true,
	},
	TERRAIN_TRAIT.LEVEL1OILREFINING : {
		"name" : "Level1OilRefining",
		"description" : "Delivers $60 per round to the controlling team, in equal portions per player turn.",
		"sprite" : load("res://sprites/terraintrait/Level1OilRefining.png"),
		"visible" : true,
	},
	TERRAIN_TRAIT.LEVEL2OILREFINING : {
		"name" : "Level2OilRefining",
		"description" : "Delivers $240 per round to the controlling team, in equal portions per player turn.",
		"sprite" : load("res://sprites/terraintrait/Level2OilRefining.png"),
		"visible" : true,
	},
	TERRAIN_TRAIT.LEVEL3OILREFINING : {
		"name" : "Level3OilRefining",
		"description" : "Delivers $480 per round to the controlling team, in equal portions per player turn.",
		"sprite" : load("res://sprites/terraintrait/Level3OilRefining.png"),
		"visible" : true,
	},
	TERRAIN_TRAIT.MISSIONCRITICAL : {
		"name" : "MissionCritical",
		"description" : "Losing this structure means defeat (or victory!).",
		"sprite" : load("res://sprites/terraintrait/MissionCritical.png"),
		"visible" : true,
	},
	TERRAIN_TRAIT.SHORE : {
		"name" : "Shore",
		"description" : "I am a shore, sure!",
		"sprite" : load("res://sprites/terraintrait/Shore.png"),
		"visible" : true,
	},
	#TERRAIN_TRAIT.REDUCEDEFFICIENCY : {
		#"name" : "ReducedEfficiency",
		#"description" : "When running at reduced efficiency, this structure provides 50% less resources.",
		#"sprite" : load(),
		#"visible" : true,
	#},
}
var unitdata: Dictionary = load("res://unit.json").data

enum UNIT{
	ANNIHILATORTANK,WARMACHINE,JAMMERTRUCK,BLOCKADE,LANCERTANK,SPIDERTANK,HEAVYCOMMANDO,
	STRIKECOMMANDO,FLAKTANK,SCORPIONTANK,MORTARTRUCK,ROCKETTRUCK,TURRET,STEALTHTANK,
	ALBATROSSTRANSPORT,RAPTORFIGHTER,VULTUREDRONE,CONDORBOMBER,LEVIATHANBARGE,HUNTERSUPPORT,
	CORVETTEFIGHTER,UBOAT,BATTLECRUISER,INTREPID,
}

var UNIT_FRAME = {
	UNIT.ANNIHILATORTANK : load("res://sprites/unitframes/annihilator.tres"),
	UNIT.WARMACHINE : load("res://sprites/unitframes/warmachine.tres"),
	UNIT.JAMMERTRUCK : load("res://sprites/unitframes/jammer.tres"),
	UNIT.BLOCKADE : load("res://sprites/unitframes/blockade.tres"),
	UNIT.LANCERTANK: load("res://sprites/unitframes/lancer.tres"),
	UNIT.SPIDERTANK: load("res://sprites/unitframes/spider.tres"),
	UNIT.HEAVYCOMMANDO: load("res://sprites/unitframes/hcommando.tres"),
	UNIT.STRIKECOMMANDO: load("res://sprites/unitframes/commando.tres"),
	UNIT.FLAKTANK: load("res://sprites/unitframes/flak.tres"),
	UNIT.SCORPIONTANK: load("res://sprites/unitframes/scorpion.tres"),
	UNIT.MORTARTRUCK: load("res://sprites/unitframes/mortar.tres"),
	UNIT.ROCKETTRUCK: load("res://sprites/unitframes/rocket.tres"),
	UNIT.TURRET: load("res://sprites/unitframes/turret.tres"),
	UNIT.STEALTHTANK: load("res://sprites/unitframes/stealth.tres"),
	UNIT.ALBATROSSTRANSPORT: load("res://sprites/unitframes/albatross.tres"),
	UNIT.RAPTORFIGHTER: load("res://sprites/unitframes/raptor.tres"),
	UNIT.VULTUREDRONE: load("res://sprites/unitframes/vulture.tres"),
	UNIT.CONDORBOMBER: load("res://sprites/unitframes/condor.tres"),
	UNIT.LEVIATHANBARGE: load("res://sprites/unitframes/leviathan.tres"),
	UNIT.HUNTERSUPPORT: load("res://sprites/unitframes/hunter.tres"),
	UNIT.CORVETTEFIGHTER: load("res://sprites/unitframes/condor.tres"),
	UNIT.UBOAT: load("res://sprites/unitframes/uboat.tres"),
	UNIT.BATTLECRUISER: load("res://sprites/unitframes/battlecruiser.tres"),
	UNIT.INTREPID: load("res://sprites/unitframes/intrepid.tres"),
}
var UNIT_AUDIO = {
	UNIT.ANNIHILATORTANK : null,
	UNIT.BATTLECRUISER : null
}

var UNIT_DATA = {
	UNIT.ANNIHILATORTANK : {
		"player" : 0,
		"color" :[],
		"team" : 0,
		"unitid" : 0,
		"unitname" : "",
		"name": "Annihilator Tank",
		"description": "The mammoth Annihilator packs a big punch and knows how to take a beating.",
		"unitsprite": UNIT_FRAME[UNIT.ANNIHILATORTANK],
		"unitaudio": "Annihilator Tank",
		"type": UNIT_TYPE.GROUND,
		"maxhp": 140,
		"hp": 140,
		"movement": UNIT_MOVEMENT.TRACKED,
		"speed": 4,
		"attack": 70,
		"armor": UNIT_ARMOR.HEAVY,
		"weapon": UNIT_WEAPON.HEAVY,
		"rangemin": 1,
		"rangemax": 1,
		"traits": [UNIT_TRAIT.MAMMOTH],
		"cost": 525,
		"direction" : "e",
		"actioned" : false,
		"isinvisible" : false,
		"unitflag" : [],
		"resource" : 0
	},
	UNIT.WARMACHINE : {
		"player" : 0,
		"color" :[],
		"team" : 0,
		"unitid" : 0,
		"unitname" : "",
		"name": "Warmachine",
		"description": "The Warmachine is the cornerstone of your army.",
		"unitsprite": UNIT_FRAME[UNIT.WARMACHINE],
		"unitaudio": "Annihilator Tank",
		"type": UNIT_TYPE.GROUND,
		"maxhp": 75,
		"hp": 75,
		"movement": UNIT_MOVEMENT.TRACKED,
		"speed": 3,
		"attack": 30,
		"armor": UNIT_ARMOR.MEDIUM,
		"weapon": UNIT_WEAPON.MEDIUM,
		"rangemin": 2,
		"rangemax": 3,
		"traits": [UNIT_TRAIT.CONSTRUCTOR,UNIT_TRAIT.SKYSWEEPER,UNIT_TRAIT.EXTRACTOR,UNIT_TRAIT.LINCHPIN,UNIT_TRAIT.UNBUILDABLE],
		"cost": 3000,
		"direction" : "e",
		"actioned" : false,
		"isinvisible" : false,
		"unitflag" : [],
		"resource" : 0
	},
	UNIT.JAMMERTRUCK : {
		"player" : 0,
		"color" :[],
		"team" : 0,
		"unitid" : 0,
		"unitname" : "",
		"name": "Jammer Truck",
		"description": "The Jammer is effective at neutralizing cloak bonuses and air raids.",
		"unitsprite": UNIT_FRAME[UNIT.JAMMERTRUCK],
		"unitaudio": "Annihilator Tank",
		"type": UNIT_TYPE.GROUND,
		"maxhp": 50,
		"hp": 50,
		"movement": UNIT_MOVEMENT.WHEELED,
		"speed": 5,
		"attack": 0,
		"armor": UNIT_ARMOR.LIGHT,
		"weapon": UNIT_WEAPON.NONE,
		"rangemin": 0,
		"rangemax": 0,
		"traits": [UNIT_TRAIT.RADAR,UNIT_TRAIT.JAMMING],
		"cost": 300,
		"direction" : "e",
		"actioned" : false,
		"isinvisible" : false,
		"unitflag" : [],
		"resource" : 0
	},
	UNIT.BLOCKADE : {
		"player" : 0,
		"color" :[],
		"team" : 0,
		"unitid" : 0,
		"unitname" : "",
		"name": "Blockade",
		"description": "Blockades get in the way of stuff.",
		"unitsprite": UNIT_FRAME[UNIT.BLOCKADE],
		"unitaudio": "Annihilator Tank",
		"type": UNIT_TYPE.GROUND,
		"maxhp": 70,
		"hp": 70,
		"movement": UNIT_MOVEMENT.TRACKED,
		"speed": 0,
		"attack": 0,
		"armor": UNIT_ARMOR.MEDIUM,
		"weapon": UNIT_WEAPON.NONE,
		"rangemin": 0,
		"rangemax": 0,
		"traits": [UNIT_TRAIT.IRREPARABLE,UNIT_TRAIT.FIXED,UNIT_TRAIT.UNBUILDABLE,UNIT_TRAIT.UNBUILDABLE],
		"cost": 40,
		"direction" : "e",
		"actioned" : false,
		"isinvisible" : false,
		"unitflag" : [],
		"resource" : 0
	},
	UNIT.LANCERTANK : {
		"player" : 0,
		"color" :[],
		"team" : 0,
		"unitid" : 0,
		"unitname" : "",
		"name": "Lancer Tank",
		"description": "Lancer attacks will hit any unit behind the one you targetted.",
		"unitsprite": UNIT_FRAME[UNIT.LANCERTANK],
		"unitaudio": "Annihilator Tank",
		"type": UNIT_TYPE.GROUND,
		"maxhp": 70,
		"hp": 70,
		"movement": UNIT_MOVEMENT.TRACKED,
		"speed": 6,
		"attack": 35,
		"armor": UNIT_ARMOR.MEDIUM,
		"weapon": UNIT_WEAPON.MEDIUM,
		"rangemin": 1,
		"rangemax": 1,
		"traits": [UNIT_TRAIT.PIERCING],
		"cost": 270,
		"direction" : "e",
		"actioned" : false,
		"isinvisible" : false,
		"unitflag" : [],
		"resource" : 0
	},
	UNIT.SPIDERTANK : {
		"player" : 0,
		"color" :[],
		"team" : 0,
		"unitid" : 0,
		"unitname" : "",
		"name": "Spider Tank",
		"description": "The Spider Tank stuns its target to avoid counter attack.",
		"unitsprite": UNIT_FRAME[UNIT.SPIDERTANK],
		"unitaudio": "Annihilator Tank",
		"type": UNIT_TYPE.GROUND,
		"maxhp": 32,
		"hp": 32,
		"movement": UNIT_MOVEMENT.FEET,
		"speed": 4,
		"attack": 55,
		"armor": UNIT_ARMOR.LIGHT,
		"weapon": UNIT_WEAPON.LIGHT,
		"rangemin": 1,
		"rangemax": 1,
		"traits": [UNIT_TRAIT.STUN],
		"cost": 250,
		"direction" : "e",
		"actioned" : false,
		"isinvisible" : false,
		"unitflag" : [],
		"resource" : 0
	},
	UNIT.HEAVYCOMMANDO : {
		"player" : 0,
		"color" :[],
		"team" : 0,
		"unitid" : 0,
		"unitname" : "",
		"name": "Heavy Commando",
		"description": "Heavies like to engage tanks and capture properties.",
		"unitsprite": UNIT_FRAME[UNIT.HEAVYCOMMANDO],
		"unitaudio": "Annihilator Tank",
		"type": UNIT_TYPE.GROUND,
		"maxhp": 40,
		"hp": 40,
		"movement": UNIT_MOVEMENT.FEET,
		"speed": 3,
		"attack": 35,
		"armor": UNIT_ARMOR.HEAVY,
		"weapon": UNIT_WEAPON.LIGHT,
		"rangemin": 1,
		"rangemax": 1,
		"traits": [UNIT_TRAIT.CAPTURE,UNIT_TRAIT.TRACKING],
		"cost": 100,
		"direction" : "e",
		"actioned" : false,
		"isinvisible" : false,
		"unitflag" : [],
		"resource" : 0
	},
	UNIT.STRIKECOMMANDO : {
		"player" : 0,
		"color" :[],
		"team" : 0,
		"unitid" : 0,
		"unitname" : "",
		"name": "Strike Commando",
		"description": "Enemy Commandos and Trucks fear the property-capturing Strike Commando.",
		"unitsprite": UNIT_FRAME[UNIT.STRIKECOMMANDO],
		"unitaudio": "Annihilator Tank",
		"type": UNIT_TYPE.GROUND,
		"maxhp": 40,
		"hp": 40,
		"movement": UNIT_MOVEMENT.FEET,
		"speed": 3,
		"attack": 28,
		"armor": UNIT_ARMOR.LIGHT,
		"weapon": UNIT_WEAPON.LIGHT,
		"rangemin": 1,
		"rangemax": 1,
		"traits": [UNIT_TRAIT.CAPTURE,UNIT_TRAIT.TRACKING],
		"cost": 75,
		"direction" : "e",
		"actioned" : false,
		"isinvisible" : false,
		"unitflag" : [],
		"resource" : 0
	},
	UNIT.FLAKTANK : {
		"player" : 0,
		"color" :[],
		"team" : 0,
		"unitid" : 0,
		"unitname" : "",
		"name": "Flak Tank",
		"description": "The Flak Tank's cannon shreds aircraft and lightly armored units to pieces.",
		"unitsprite": UNIT_FRAME[UNIT.FLAKTANK],
		"unitaudio": "Annihilator Tank",
		"type": UNIT_TYPE.GROUND,
		"maxhp": 70,
		"hp": 70,
		"movement": UNIT_MOVEMENT.TRACKED,
		"speed": 5,
		"attack": 17,
		"armor": UNIT_ARMOR.MEDIUM,
		"weapon": UNIT_WEAPON.LIGHT,
		"rangemin": 1,
		"rangemax": 1,
		"traits": [UNIT_TRAIT.FLAK,UNIT_TRAIT.SKYSWEEPER],
		"cost": 240,
		"direction" : "e",
		"actioned" : false,
		"isinvisible" : false,
		"unitflag" : [],
		"resource" : 0
	},
	UNIT.SCORPIONTANK : {
		"player" : 0,
		"color" :[],
		"team" : 0,
		"unitid" : 0,
		"unitname" : "",
		"name": "Scorpion Tank",
		"description": "The versatile Scorpion Tank is the back bone of most armed forces.",
		"unitsprite": UNIT_FRAME[UNIT.SCORPIONTANK],
		"unitaudio": "Annihilator Tank",
		"type": UNIT_TYPE.GROUND,
		"maxhp": 70,
		"hp": 70,
		"movement": UNIT_MOVEMENT.TRACKED,
		"speed": 6,
		"attack": 35,
		"armor": UNIT_ARMOR.MEDIUM,
		"weapon": UNIT_WEAPON.MEDIUM,
		"rangemin": 1,
		"rangemax": 1,
		"traits": [UNIT_TRAIT.BLITZ],
		"cost": 270,
		"direction" : "e",
		"actioned" : false,
		"isinvisible" : false,
		"unitflag" : [],
		"resource" : 0
	},
	UNIT.MORTARTRUCK : {
		"player" : 0,
		"color" :[],
		"team" : 0,
		"unitid" : 0,
		"unitname" : "",
		"name": "Mortar Truck",
		"description": "The Mortar Truck is a general purpose cost-effective medium range artillery unit.",
		"unitsprite": UNIT_FRAME[UNIT.MORTARTRUCK],
		"unitaudio": "Annihilator Tank",
		"type": UNIT_TYPE.GROUND,
		"maxhp": 50,
		"hp": 50,
		"movement": UNIT_MOVEMENT.WHEELED,
		"speed": 5,
		"attack": 48,
		"armor": UNIT_ARMOR.LIGHT,
		"weapon": UNIT_WEAPON.LIGHT,
		"rangemin": 2,
		"rangemax": 3,
		"traits": [UNIT_TRAIT.COUNTERBATTERY],
		"cost": 285,
		"direction" : "e",
		"actioned" : false,
		"isinvisible" : false,
		"unitflag" : [],
		"resource" : 0
	},
	UNIT.ROCKETTRUCK : {
		"player" : 0,
		"color" :[],
		"team" : 0,
		"unitid" : 0,
		"unitname" : "",
		"name": "Rocket Truck",
		"description": "Specialized long range unit that can fire on enemy aircraft and tanks.",
		"unitsprite": UNIT_FRAME[UNIT.ROCKETTRUCK],
		"unitaudio": "Annihilator Tank",
		"type": UNIT_TYPE.GROUND,
		"maxhp": 40,
		"hp": 40,
		"movement": UNIT_MOVEMENT.WHEELED,
		"speed": 4,
		"attack": 40,
		"armor": UNIT_ARMOR.LIGHT,
		"weapon": UNIT_WEAPON.HEAVY,
		"rangemin": 3,
		"rangemax": 5,
		"traits": [UNIT_TRAIT.COUNTERBATTERY,UNIT_TRAIT.SKYSWEEPER,UNIT_TRAIT.ANTISUB],
		"cost": 470,
		"direction" : "e",
		"actioned" : false,
		"isinvisible" : false,
		"unitflag" : [],
		"resource" : 0
	},
	UNIT.TURRET : {
		"player" : 0,
		"color" :[],
		"team" : 0,
		"unitid" : 0,
		"unitname" : "",
		"name": "Turret",
		"description": "This immobile defensive unit helps deter both ground, sea and air invasions.",
		"unitsprite": UNIT_FRAME[UNIT.TURRET],
		"unitaudio": "Annihilator Tank",
		"type": UNIT_TYPE.GROUND,
		"maxhp": 100,
		"hp": 100,
		"movement": UNIT_MOVEMENT.NONE,
		"speed": 0,
		"attack": 40,
		"armor": UNIT_ARMOR.HEAVY,
		"weapon": UNIT_WEAPON.MEDIUM,
		"rangemin": 2,
		"rangemax": 5,
		"traits": [UNIT_TRAIT.MAINTENANCE,UNIT_TRAIT.SKYSWEEPER,UNIT_TRAIT.FIXED,UNIT_TRAIT.UNBUILDABLE],
		"cost": 100,
		"direction" : "e",
		"actioned" : false,
		"isinvisible" : false,
		"unitflag" : [],
		"resource" : 0
	},
	UNIT.STEALTHTANK : {
		"player" : 0,
		"color" :[],
		"team" : 0,
		"unitid" : 0,
		"unitname" : "",
		"name": "Stealth Tank",
		"description": "Stealth attack bonuses make this a powerful weapon in the hands of a capable general.",
		"unitsprite": UNIT_FRAME[UNIT.STEALTHTANK],
		"unitaudio": "Annihilator Tank",
		"type": UNIT_TYPE.GROUND,
		"maxhp": 40,
		"hp": 40,
		"movement": UNIT_MOVEMENT.TRACKED,
		"speed": 5,
		"attack": 30,
		"armor": UNIT_ARMOR.MEDIUM,
		"weapon": UNIT_WEAPON.MEDIUM,
		"rangemin": 1,
		"rangemax": 1,
		"traits": [UNIT_TRAIT.CLOAKING],
		"cost": 340,
		"direction" : "e",
		"actioned" : false,
		"isinvisible" : false,
		"unitflag" : [],
		"resource" : 0
	},
	UNIT.ALBATROSSTRANSPORT : {
		"player" : 0,
		"color" :[],
		"team" : 0,
		"unitid" : 0,
		"unitname" : "",
		"name": "Albatross Transport",
		"description": "The Albatross is the fastest way to move Commandos around the map.",
		"unitsprite": UNIT_FRAME[UNIT.ALBATROSSTRANSPORT],
		"unitaudio": "Annihilator Tank",
		"type": UNIT_TYPE.WINGS,
		"maxhp": 50,
		"hp": 50,
		"movement": UNIT_MOVEMENT.WINGS,
		"speed": 6,
		"attack": 0,
		"armor": UNIT_ARMOR.LIGHT,
		"weapon": UNIT_WEAPON.NONE,
		"rangemin": 0,
		"rangemax": 0,
		"traits": [UNIT_TRAIT.TRANSPORT,UNIT_TRAIT.UNBUILDABLE],
		"cost": 20,
		"direction" : "e",
		"actioned" : false,
		"isinvisible" : false,
		"unitflag" : [],
		"resource" : 0
	},
	UNIT.RAPTORFIGHTER : {
		"player" : 0,
		"color" :[],
		"team" : 0,
		"unitid" : 0,
		"unitname" : "",
		"name": "Raptor Fighter",
		"description": "Effective at engaging air, sea and ground targets.",
		"unitsprite": UNIT_FRAME[UNIT.RAPTORFIGHTER],
		"unitaudio": "Annihilator Tank",
		"type": UNIT_TYPE.WINGS,
		"maxhp": 50,
		"hp": 50,
		"movement": UNIT_MOVEMENT.WINGS,
		"speed": 7,
		"attack": 25,
		"armor": UNIT_ARMOR.LIGHT,
		"weapon": UNIT_WEAPON.LIGHT,
		"rangemin": 1,
		"rangemax": 1,
		"traits": [],
		"cost": 400,
		"direction" : "e",
		"actioned" : false,
		"isinvisible" : false,
		"unitflag" : [UNIT_TRAIT.SKYSWEEPER,UNIT_TRAIT.IRREPARABLE],
		"resource" : 0
	},
	UNIT.VULTUREDRONE : {
		"player" : 0,
		"color" :[],
		"team" : 0,
		"unitid" : 0,
		"unitname" : "",
		"name": "Vulture Drone",
		"description": "A specialized scavenger that can move and attack again, if it kills its target.",
		"unitsprite": UNIT_FRAME[UNIT.VULTUREDRONE],
		"unitaudio": "Annihilator Tank",
		"type": UNIT_TYPE.WINGS,
		"maxhp": 55,
		"hp": 55,
		"movement": UNIT_MOVEMENT.WINGS,
		"speed": 5,
		"attack": 30,
		"armor": UNIT_ARMOR.LIGHT,
		"weapon": UNIT_WEAPON.MEDIUM,
		"rangemin": 1,
		"rangemax": 1,
		"traits": [UNIT_TRAIT.SCAVENGE],
		"cost": 550,
		"direction" : "e",
		"actioned" : false,
		"isinvisible" : false,
		"unitflag" : [],
		"resource" : 0
	},
	UNIT.CONDORBOMBER : {
		"player" : 0,
		"color" :[],
		"team" : 0,
		"unitid" : 0,
		"unitname" : "",
		"name": "Condor Bomber",
		"description": "The Condor Bomber is as hardy as it is powerful. It fears only the enemy Raptor.",
		"unitsprite": UNIT_FRAME[UNIT.CONDORBOMBER],
		"unitaudio": "Annihilator Tank",
		"type": UNIT_TYPE.WINGS,
		"maxhp": 72,
		"hp": 72,
		"movement": UNIT_MOVEMENT.WINGS,
		"speed": 3,
		"attack": 70,
		"armor": UNIT_ARMOR.LIGHT,
		"weapon": UNIT_WEAPON.HEAVY,
		"rangemin": 1,
		"rangemax": 1,
		"traits": [UNIT_TRAIT.ANTISUB,UNIT_TRAIT.BLINDSPOT],
		"cost": 600,
		"direction" : "e",
		"actioned" : false,
		"isinvisible" : false,
		"unitflag" : [],
		"resource" : 0
	},
	UNIT.LEVIATHANBARGE : {
		"player" : 0,
		"color" :[],
		"team" : 0,
		"unitid" : 0,
		"unitname" : "",
		"name": "Leviathan Barge",
		"description": "Leviathans transport ground units across the oceans.",
		"unitsprite": UNIT_FRAME[UNIT.LEVIATHANBARGE],
		"unitaudio": "Annihilator Tank",
		"type": UNIT_TYPE.SEA,
		"maxhp": 60,
		"hp": 60,
		"movement": UNIT_MOVEMENT.SHALLOWWATER,
		"speed": 4,
		"attack": 0,
		"armor": UNIT_ARMOR.MEDIUM,
		"weapon": UNIT_WEAPON.NONE,
		"rangemin": 0,
		"rangemax": 0,
		"traits": [UNIT_TRAIT.TRANSPORT,UNIT_TRAIT.UNBUILDABLE],
		"cost": 35,
		"direction" : "e",
		"actioned" : false,
		"isinvisible" : false,
		"unitflag" : [],
		"resource" : 0
	},
	UNIT.HUNTERSUPPORT : {
		"player" : 0,
		"color" :[],
		"team" : 0,
		"unitid" : 0,
		"unitname" : "",
		"name": "Hunter Support",
		"description": "Hunters excel at keeping the oceans clear of enemy aircraft and U-boats.",
		"unitsprite": UNIT_FRAME[UNIT.HUNTERSUPPORT],
		"unitaudio": "Annihilator Tank",
		"type": UNIT_TYPE.SEA,
		"maxhp": 90,
		"hp": 90,
		"movement": UNIT_MOVEMENT.SHALLOWWATER,
		"speed": 5,
		"attack": 17,
		"armor": UNIT_ARMOR.MEDIUM,
		"weapon": UNIT_WEAPON.LIGHT,
		"rangemin": 1,
		"rangemax": 1,
		"traits": [UNIT_TRAIT.SKYSWEEPER,UNIT_TRAIT.ANTISUB,UNIT_TRAIT.FLAK,UNIT_TRAIT.SEABOUND,UNIT_TRAIT.TRACKING],
		"cost": 450,
		"direction" : "e",
		"actioned" : false,
		"isinvisible" : false,
		"unitflag" : [],
		"resource" : 0
	},
	UNIT.CORVETTEFIGHTER : {
		"player" : 0,
		"color" :[],
		"team" : 0,
		"unitid" : 0,
		"unitname" : "",
		"name": "Corvette Fighter",
		"description": "The Corvette is the brawler of the seas, capable of engaging most enemy targets effectively.",
		"unitsprite": UNIT_FRAME[UNIT.CORVETTEFIGHTER],
		"unitaudio": "Annihilator Tank",
		"type": UNIT_TYPE.SEA,
		"maxhp": 90,
		"hp": 90,
		"movement": UNIT_MOVEMENT.DEEPWATER,
		"speed": 5,
		"attack": 45,
		"armor": UNIT_ARMOR.MEDIUM,
		"weapon": UNIT_WEAPON.MEDIUM,
		"rangemin": 1,
		"rangemax": 1,
		"traits": [UNIT_TRAIT.BLITZ,UNIT_TRAIT.MASSIVEHULL],
		"cost": 500,
		"direction" : "e",
		"actioned" : false,
		"isinvisible" : false,
		"unitflag" : [],
		"resource" : 0
	},
	UNIT.UBOAT : {
		"player" : 0,
		"color" :[],
		"team" : 0,
		"unitid" : 0,
		"unitname" : "",
		"name": "U-Boat",
		"description": "The U-boat's cloak is useful for holding choke points and attacking an entrenched foe.",
		"unitsprite": UNIT_FRAME[UNIT.UBOAT],
		"unitaudio": "Annihilator Tank",
		"type": UNIT_TYPE.SEA,
		"maxhp": 25,
		"hp": 25,
		"movement": UNIT_MOVEMENT.SHALLOWWATER,
		"speed": 4,
		"attack": 35,
		"armor": UNIT_ARMOR.LIGHT,
		"weapon": UNIT_WEAPON.HEAVY,
		"rangemin": 1,
		"rangemax": 1,
		"traits": [UNIT_TRAIT.SEABOUND,UNIT_TRAIT.ANTISUB,UNIT_TRAIT.SUBMERGED,UNIT_TRAIT.CLOAKING],
		"cost": 475,
		"direction" : "e",
		"actioned" : false,
		"isinvisible" : false,
		"unitflag" : [],
		"resource" : 0
	},
	UNIT.BATTLECRUISER : {
		"player" : 0,
		"color" :[],
		"team" : 0,
		"unitid" : 0,
		"unitname" : "",
		"name": "Battlecruiser",
		"description": "The massive guns of the Battlecruiser can fire further than all other units.",
		"unitsprite": UNIT_FRAME[UNIT.BATTLECRUISER],
		"unitaudio": "Annihilator Tank",
		"type": UNIT_TYPE.SEA,
		"maxhp": 140,
		"hp": 140,
		"movement": UNIT_MOVEMENT.DEEPWATER,
		"speed": 4,
		"attack": 50,
		"armor": UNIT_ARMOR.HEAVY,
		"weapon": UNIT_WEAPON.HEAVY,
		"rangemin": 3,
		"rangemax": 6,
		"traits": [UNIT_TRAIT.MASSIVEHULL,UNIT_TRAIT.COUNTERBATTERY],
		"cost": 800,
		"direction" : "e",
		"actioned" : false,
		"isinvisible" : false,
		"unitflag" : [],
		"resource" : 0
	},
	UNIT.INTREPID : {
		"player" : 0,
		"color" :[],
		"team" : 0,
		"unitid" : 0,
		"unitname" : "",
		"name": "Intrepid",
		"description": "Use the Intrepid to capture sea properties and warfactories along coast lines.",
		"unitsprite": UNIT_FRAME[UNIT.INTREPID],
		"unitaudio": "Annihilator Tank",
		"type": UNIT_TYPE.SEA,
		"maxhp": 50,
		"hp": 50,
		"movement": UNIT_MOVEMENT.SHALLOWWATER,
		"speed": 5,
		"attack": 15,
		"armor": UNIT_ARMOR.LIGHT,
		"weapon": UNIT_WEAPON.LIGHT,
		"rangemin": 1,
		"rangemax": 1,
		"traits": [UNIT_TRAIT.CAPTURE,UNIT_TRAIT.SEABOUND],
		"cost": 200,
		"direction" : "e",
		"actioned" : false,
		"isinvisible" : false,
		"unitflag" : [],
		"resource" : 0
	},
}

enum TERRAIN{
	PLAINS=0,SEA=9,ROAD=2,FOREST=1,MOUNTAIN=4,DESERT=5,REEF=15,SHORE=16,
	HILL=3,CANYON=12,WASTELAND=13,VOLCANO=14,ARCHIPELAGO=17,ROCKFORMATION=18,
	BRIDGE=10,HIGHBRIDGE=11,
	ENRICHEDOREDEPOSIT=8,OREDEPOSIT=7,DEPLETEDOREDEPOSIT=6,
	aaaaaaaaa=999,
}

var TERRAIN_DATA = {
	TERRAIN.PLAINS : {
		"name": "Plains",
		"description": "Plains slow movement slightly but provide some minimal cover against enemy attacks.",
		"traits": [TERRAIN_TRAIT.GROUND,TERRAIN_TRAIT.UNEVEN,TERRAIN_TRAIT.COVER],
		UNIT_MOVEMENT.NONE : INF,
		UNIT_MOVEMENT.FEET : 1.0,
		UNIT_MOVEMENT.WHEELED : 1.5,
		UNIT_MOVEMENT.TRACKED : 1.0,
		UNIT_MOVEMENT.WINGS : 1.0,
		UNIT_MOVEMENT.SHALLOWWATER : INF,
		UNIT_MOVEMENT.DEEPWATER : INF,
		"grounddefense" : 0.1,
		"airdefense" : 0,
		"seadefense" : 0.1,
		"damagetoground" : 0,
		"damagetoair" : 0,
		"damagetosea" : 0,
	},
	TERRAIN.SEA : {
		"name": "Sea",
		"description": "The open sea forms the theater for naval combat.",
		"traits": [TERRAIN_TRAIT.WATER],
		UNIT_MOVEMENT.NONE : INF,
		UNIT_MOVEMENT.FEET : INF,
		UNIT_MOVEMENT.WHEELED : INF,
		UNIT_MOVEMENT.TRACKED : INF,
		UNIT_MOVEMENT.WINGS : 1.0,
		UNIT_MOVEMENT.SHALLOWWATER : 1.0,
		UNIT_MOVEMENT.DEEPWATER : 1.0,
		"grounddefense" : 0,
		"airdefense" : 0,
		"seadefense" : 0,
		"damagetoground" : 0,
		"damagetoair" : 0,
		"damagetosea" : 0,
	},
	TERRAIN.ROAD : {
		"name": "Road",
		"description": "Roads help slower ground units cover long distances quickly, but provide no defensive cover.",
		"traits": [TERRAIN_TRAIT.WATER],
		UNIT_MOVEMENT.NONE : INF,
		UNIT_MOVEMENT.FEET : 1.0,
		UNIT_MOVEMENT.WHEELED : 1.0,
		UNIT_MOVEMENT.TRACKED : 1.0,
		UNIT_MOVEMENT.WINGS : 1.0,
		UNIT_MOVEMENT.SHALLOWWATER : INF,
		UNIT_MOVEMENT.DEEPWATER : INF,
		"grounddefense" : 0,
		"airdefense" : 0,
		"seadefense" : 0,
		"damagetoground" : 0,
		"damagetoair" : 0,
		"damagetosea" : 0,
	},
	TERRAIN.FOREST : {
		"name": "Forest",
		"description": "Forests will slow wheeled and tracked units, but will provide defensive cover from attacks.",
		"traits": [TERRAIN_TRAIT.GROUND,TERRAIN_TRAIT.RUGGED,TERRAIN_TRAIT.CAMOUFLAGE],
		UNIT_MOVEMENT.NONE : INF,
		UNIT_MOVEMENT.FEET : 1.0,
		UNIT_MOVEMENT.WHEELED : 2.5,
		UNIT_MOVEMENT.TRACKED : 2.0,
		UNIT_MOVEMENT.WINGS : 1.0,
		UNIT_MOVEMENT.SHALLOWWATER : INF,
		UNIT_MOVEMENT.DEEPWATER : INF,
		"grounddefense" : 0.2,
		"airdefense" : 0,
		"seadefense" : 0.2,
		"damagetoground" : 0,
		"damagetoair" : 0,
		"damagetosea" : 0,
	},
	TERRAIN.MOUNTAIN : {
		"name": "Mountain",
		"description": "Mountains are the best place to bunker infantry during an assault or strategic defense.",
		"traits": [TERRAIN_TRAIT.GROUND,TERRAIN_TRAIT.PRECIPITOUS,TERRAIN_TRAIT.BUNKER],
		UNIT_MOVEMENT.NONE : INF,
		UNIT_MOVEMENT.FEET : 2.0,
		UNIT_MOVEMENT.WHEELED : INF,
		UNIT_MOVEMENT.TRACKED : INF,
		UNIT_MOVEMENT.WINGS : 1.0,
		UNIT_MOVEMENT.SHALLOWWATER : INF,
		UNIT_MOVEMENT.DEEPWATER : INF,
		"grounddefense" : 0.4,
		"airdefense" : 0.4,
		"seadefense" : 0.4,
		"damagetoground" : 0,
		"damagetoair" : 0,
		"damagetosea" : 0,
	},
	TERRAIN.DESERT : {
		"name": "Desert",
		"description": "Infantry units cannot enter the desert.",
		"traits": [TERRAIN_TRAIT.GROUND,TERRAIN_TRAIT.RUGGED,TERRAIN_TRAIT.BARBED],
		UNIT_MOVEMENT.NONE : INF,
		UNIT_MOVEMENT.FEET : INF,
		UNIT_MOVEMENT.WHEELED : 2.5,
		UNIT_MOVEMENT.TRACKED : 2.0,
		UNIT_MOVEMENT.WINGS : 1.0,
		UNIT_MOVEMENT.SHALLOWWATER : INF,
		UNIT_MOVEMENT.DEEPWATER : INF,
		"grounddefense" : 0,
		"airdefense" : 0,
		"seadefense" : 0,
		"damagetoground" : 0,
		"damagetoair" : 0,
		"damagetosea" : 0,
	},
	TERRAIN.REEF : {
		"name": "Reef",
		"description": "Reefs slow movement and improves defense against attack.",
		"traits": [TERRAIN_TRAIT.WATER,TERRAIN_TRAIT.TRICKYWATERS,TERRAIN_TRAIT.COVER],
		UNIT_MOVEMENT.NONE : INF,
		UNIT_MOVEMENT.FEET : INF,
		UNIT_MOVEMENT.WHEELED : INF,
		UNIT_MOVEMENT.TRACKED : INF,
		UNIT_MOVEMENT.WINGS : 1.0,
		UNIT_MOVEMENT.SHALLOWWATER : 2.0,
		UNIT_MOVEMENT.DEEPWATER : 3,
		"grounddefense" : 0.1,
		"airdefense" : 0,
		"seadefense" : 0.1,
		"damagetoground" : 0,
		"damagetoair" : 0,
		"damagetosea" : 0,
	},
	TERRAIN.SHORE : {
		"name": "Shore",
		"description": "Shores are the link between the land and sea. Order Leviathan pick ups for ground troops here.",
		"traits": [TERRAIN_TRAIT.SHORE,TERRAIN_TRAIT.SHALLOW],
		UNIT_MOVEMENT.NONE : INF,
		UNIT_MOVEMENT.FEET : 1.0,
		UNIT_MOVEMENT.WHEELED : 1.0,
		UNIT_MOVEMENT.TRACKED : 1.0,
		UNIT_MOVEMENT.WINGS : 1.0,
		UNIT_MOVEMENT.SHALLOWWATER : 1.0,
		UNIT_MOVEMENT.DEEPWATER : INF,
		"grounddefense" : 0,
		"airdefense" : 0,
		"seadefense" : 0,
		"damagetoground" : 0,
		"damagetoair" : 0,
		"damagetosea" : 0,
	},
	TERRAIN.HILL : {
		"name": "Hill",
		"description": "Hills can provide your ranged units with the boost necessary to challenge an entrenched opponent.",
		"traits": [TERRAIN_TRAIT.GROUND,TERRAIN_TRAIT.FARSIGHT,TERRAIN_TRAIT.CAMOUFLAGE,TERRAIN_TRAIT.RUGGED],
		UNIT_MOVEMENT.NONE : INF,
		UNIT_MOVEMENT.FEET : 1.0,
		UNIT_MOVEMENT.WHEELED : 2.5,
		UNIT_MOVEMENT.TRACKED : 2.0,
		UNIT_MOVEMENT.WINGS :1.0 ,
		UNIT_MOVEMENT.SHALLOWWATER : INF,
		UNIT_MOVEMENT.DEEPWATER : INF,
		"grounddefense" : 0.2,
		"airdefense" : 0,
		"seadefense" : 0.2,
		"damagetoground" : 0,
		"damagetoair" : 0,
		"damagetosea" : 0,
	},
	TERRAIN.CANYON : {
		"name": "Canyon",
		"description": "Use Canyons to avoid ranged fire when traversing an area.",
		"traits": [TERRAIN_TRAIT.GROUND,TERRAIN_TRAIT.SHIELDED],
		UNIT_MOVEMENT.NONE : INF,
		UNIT_MOVEMENT.FEET : 1.0,
		UNIT_MOVEMENT.WHEELED : 1.0,
		UNIT_MOVEMENT.TRACKED : 1.0,
		UNIT_MOVEMENT.WINGS : 1.0,
		UNIT_MOVEMENT.SHALLOWWATER : INF,
		UNIT_MOVEMENT.DEEPWATER : INF,
		"grounddefense" : 0,
		"airdefense" : 0,
		"seadefense" : 0,
		"damagetoground" : 0,
		"damagetoair" : 0,
		"damagetosea" : 0,
	},
	TERRAIN.WASTELAND : {
		"name": "Wasteland",
		"description": "Wastelands are dangerous to your units but they provide massive defensive bonuses.",
		"traits": [TERRAIN_TRAIT.GROUND,TERRAIN_TRAIT.GARRISON,TERRAIN_TRAIT.HAZARD],
		UNIT_MOVEMENT.NONE : INF,
		UNIT_MOVEMENT.FEET : 1,
		UNIT_MOVEMENT.WHEELED : 1,
		UNIT_MOVEMENT.TRACKED : 1,
		UNIT_MOVEMENT.WINGS : 1.0,
		UNIT_MOVEMENT.SHALLOWWATER : INF,
		UNIT_MOVEMENT.DEEPWATER : INF,
		"grounddefense" : 0.5,
		"airdefense" : 0,
		"seadefense" : 0.5,
		"damagetoground" : 20,
		"damagetoair" : 0,
		"damagetosea" : 20,
	},
	TERRAIN.VOLCANO : {
		"name": "Volcano",
		"description": "No unit can cross the deadly Volcano.",
		"traits": [TERRAIN_TRAIT.IMPASSABLE],
		UNIT_MOVEMENT.NONE : INF,
		UNIT_MOVEMENT.FEET : INF,
		UNIT_MOVEMENT.WHEELED : INF,
		UNIT_MOVEMENT.TRACKED : INF,
		UNIT_MOVEMENT.WINGS : INF,
		UNIT_MOVEMENT.SHALLOWWATER : INF,
		UNIT_MOVEMENT.DEEPWATER : INF,
		"grounddefense" : 0,
		"airdefense" : 0,
		"seadefense" : 0,
		"damagetoground" : 0,
		"damagetoair" : 0,
		"damagetosea" : 0,
	},
	TERRAIN.ARCHIPELAGO : {
		"name": "Archipelago",
		"description": "A cluster of small islands providing some defensive cover at the cost of mobility.",
		"traits": [TERRAIN_TRAIT.WATER,TERRAIN_TRAIT.REDUCEDMOBILITY,TERRAIN_TRAIT.CAMOUFLAGE],
		UNIT_MOVEMENT.NONE : INF,
		UNIT_MOVEMENT.FEET : INF,
		UNIT_MOVEMENT.WHEELED : INF,
		UNIT_MOVEMENT.TRACKED : INF,
		UNIT_MOVEMENT.WINGS : 1.0,
		UNIT_MOVEMENT.SHALLOWWATER : 2.0,
		UNIT_MOVEMENT.DEEPWATER : 2.0,
		"grounddefense" : 0.2,
		"airdefense" : 0,
		"seadefense" : 0.2,
		"damagetoground" : 0,
		"damagetoair" : 0,
		"damagetosea" : 0,
	},
	TERRAIN.ROCKFORMATION : {
		"name": "Rock Formation",
		"description": "The Rock Formation provides heavy defensive cover, but will damage sea units that rest on them.",
		"traits": [TERRAIN_TRAIT.WATER,TERRAIN_TRAIT.GARRISON,TERRAIN_TRAIT.HAZARD],
		UNIT_MOVEMENT.NONE : INF,
		UNIT_MOVEMENT.FEET : INF,
		UNIT_MOVEMENT.WHEELED : INF,
		UNIT_MOVEMENT.TRACKED : INF,
		UNIT_MOVEMENT.WINGS : 1.0,
		UNIT_MOVEMENT.SHALLOWWATER : INF,
		UNIT_MOVEMENT.DEEPWATER : INF,
		"grounddefense" : 0.5,
		"airdefense" : 0,
		"seadefense" : 0.5,
		"damagetoground" : 20,
		"damagetoair" : 0,
		"damagetosea" : 20,
	},
	TERRAIN.ENRICHEDOREDEPOSIT : {
		"name": "Enriched Ore Deposit",
		"description": "Warmachines can extract Ore from Enriched Ore Deposits.",
		"traits": [TERRAIN_TRAIT.EXTRACTABLE],
		UNIT_MOVEMENT.NONE : INF,
		UNIT_MOVEMENT.FEET : 1.0,
		UNIT_MOVEMENT.WHEELED : 1.0,
		UNIT_MOVEMENT.TRACKED : 1.0,
		UNIT_MOVEMENT.WINGS : 1.0,
		UNIT_MOVEMENT.SHALLOWWATER : INF,
		UNIT_MOVEMENT.DEEPWATER : INF,
		"grounddefense" : 0,
		"airdefense" : 0,
		"seadefense" : 0,
		"damagetoground" : 0,
		"damagetoair" : 0,
		"damagetosea" : 0,
	},
	TERRAIN.OREDEPOSIT : {
		"name": "Ore Deposit",
		"description": "Warmachines can extract Ore from Ore Deposits.",
		"traits": [TERRAIN_TRAIT.EXTRACTABLE],
		UNIT_MOVEMENT.NONE : INF,
		UNIT_MOVEMENT.FEET : 1.0,
		UNIT_MOVEMENT.WHEELED : 1.0,
		UNIT_MOVEMENT.TRACKED : 1.0,
		UNIT_MOVEMENT.WINGS : 1.0,
		UNIT_MOVEMENT.SHALLOWWATER : INF,
		UNIT_MOVEMENT.DEEPWATER : INF,
		"grounddefense" : 0,
		"airdefense" : 0,
		"seadefense" : 0,
		"damagetoground" : 0,
		"damagetoair" : 0,
		"damagetosea" : 0,
	},
	TERRAIN.DEPLETEDOREDEPOSIT : {
		"name": "Depleted Ore Deposit",
		"description": "Nothing else can be extracted from this tile.",
		"traits": [],
		UNIT_MOVEMENT.NONE : INF,
		UNIT_MOVEMENT.FEET : 1.0,
		UNIT_MOVEMENT.WHEELED : 1.0,
		UNIT_MOVEMENT.TRACKED : 1.0,
		UNIT_MOVEMENT.WINGS : 1.0,
		UNIT_MOVEMENT.SHALLOWWATER : INF,
		UNIT_MOVEMENT.DEEPWATER : INF,
		"grounddefense" : 0,
		"airdefense" : 0,
		"seadefense" : 0,
		"damagetoground" : 0,
		"damagetoair" : 0,
		"damagetosea" : 0,
	},
	TERRAIN.BRIDGE : {
		"name": "Bridge",
		"description": "Bridges are useful for connecting islands of land, but they lack defensive cover.",
		"traits": [TERRAIN_TRAIT.GROUND],
		UNIT_MOVEMENT.NONE : INF,
		UNIT_MOVEMENT.FEET : 1.0,
		UNIT_MOVEMENT.WHEELED : 1.0,
		UNIT_MOVEMENT.TRACKED : 1.0,
		UNIT_MOVEMENT.WINGS : 1.0,
		UNIT_MOVEMENT.SHALLOWWATER : INF,
		UNIT_MOVEMENT.DEEPWATER : INF,
		"grounddefense" : 0,
		"airdefense" : 0,
		"seadefense" : 0,
		"damagetoground" : 0,
		"damagetoair" : 0,
		"damagetosea" : 0,
	},
	TERRAIN.HIGHBRIDGE : {
		"name": "High Bridge",
		"description": "The High Bridge can be crossed by ground units and sailed under by sea units.",
		"traits": [],
		UNIT_MOVEMENT.NONE : INF,
		UNIT_MOVEMENT.FEET : 1.0,
		UNIT_MOVEMENT.WHEELED : 1.0,
		UNIT_MOVEMENT.TRACKED : 1.0,
		UNIT_MOVEMENT.WINGS : 1.0,
		UNIT_MOVEMENT.SHALLOWWATER : 1.0,
		UNIT_MOVEMENT.DEEPWATER : 1.0,
		"grounddefense" : 0,
		"airdefense" : 0,
		"seadefense" : 0,
		"damagetoground" : 0,
		"damagetoair" : 0,
		"damagetosea" : 0,
	},
	#TERRAIN. : {
		#"name": "",
		#"description": "",
		#"traits": [],
		#UNIT_MOVEMENT.NONE : INF,
		#UNIT_MOVEMENT.FEET : INF,
		#UNIT_MOVEMENT.WHEELED : INF,
		#UNIT_MOVEMENT.TRACKED : INF,
		#UNIT_MOVEMENT.WINGS : 1.0,
		#UNIT_MOVEMENT.SHALLOWWATER : INF,
		#UNIT_MOVEMENT.DEEPWATER : INF,
		#"grounddefense" : 0,
		#"airdefense" : 0,
		#"seadefense" : 0,
		#"damagetoground" : 0,
		#"damagetoair" : 0,
		#"damagetosea" : 0,
	#},
	#TERRAIN. : {
		#"name": "",
		#"description": "",
		#"traits": [],
		#UNIT_MOVEMENT.NONE : INF,
		#UNIT_MOVEMENT.FEET : INF,
		#UNIT_MOVEMENT.WHEELED : INF,
		#UNIT_MOVEMENT.TRACKED : INF,
		#UNIT_MOVEMENT.WINGS : 1.0,
		#UNIT_MOVEMENT.SHALLOWWATER : INF,
		#UNIT_MOVEMENT.DEEPWATER : INF,
		#"grounddefense" : 0,
		#"airdefense" : 0,
		#"seadefense" : 0,
		#"damagetoground" : 0,
		#"damagetoair" : 0,
		#"damagetosea" : 0,
	#},
}

enum BUILDING{
	COMMANDCENTER,GROUNDCONTROL,AIRCONTROL,SEACONTROL,FACTORY,
	OILREFINERY,ADVANCEDOILREFINERY,OILRIG,
}
var BUILDING_DATA = {
	BUILDING.COMMANDCENTER : {
		"name": "Command Center",
		"description": "This is your base of operations. Do not allow the enemy to capture any Command Center.",
		"traits": [TERRAIN_TRAIT.GROUND,TERRAIN_TRAIT.CAPTURABLE,TERRAIN_TRAIT.GARRISON,TERRAIN_TRAIT.MISSIONCRITICAL],
		"sprite" : load("res://sprites/building/147_capital_capital.png"),
		UNIT_MOVEMENT.NONE : INF,
		UNIT_MOVEMENT.FEET : 1.0,
		UNIT_MOVEMENT.WHEELED : 1.0,
		UNIT_MOVEMENT.TRACKED : 1.0,
		UNIT_MOVEMENT.WINGS : 1.0,
		UNIT_MOVEMENT.SHALLOWWATER : INF,
		UNIT_MOVEMENT.DEEPWATER : INF,
		"grounddefense" : 0.5,
		"airdefense" : 0,
		"seadefense" : 0.5,
		"damagetoground" : 0,
		"damagetoair" : 0,
		"damagetosea" : 0,
	},
	BUILDING.GROUNDCONTROL : {
		"name": "Ground Control",
		"description": "Ground Controls enable ground unit manufacturing at your warfactories.",
		"traits": [TERRAIN_TRAIT.GROUND,TERRAIN_TRAIT.CAPTURABLE,TERRAIN_TRAIT.GROUNDPROFICIENCY,TERRAIN_TRAIT.COVER],
		"sprite" : load("res://sprites/building/446_groundcontrol_groundcontrol.png"),
		UNIT_MOVEMENT.NONE : INF,
		UNIT_MOVEMENT.FEET : 1.0,
		UNIT_MOVEMENT.WHEELED : 1.0,
		UNIT_MOVEMENT.TRACKED : 1.0,
		UNIT_MOVEMENT.WINGS : 1.0,
		UNIT_MOVEMENT.SHALLOWWATER : INF,
		UNIT_MOVEMENT.DEEPWATER : INF,
		"grounddefense" : 0.1,
		"airdefense" : 0,
		"seadefense" : 0.1,
		"damagetoground" : 0,
		"damagetoair" : 0,
		"damagetosea" : 0,
	},
	BUILDING.AIRCONTROL : {
		"name": "Air Control",
		"description": "Air Controls enable air unit manufacturing at your warfactories.",
		"traits": [TERRAIN_TRAIT.GROUND,TERRAIN_TRAIT.CAPTURABLE,TERRAIN_TRAIT.AIRPROFICIENCY,TERRAIN_TRAIT.COVER],
		"sprite" : load("res://sprites/building/571_aircontrol_aircontrol.png"),
		UNIT_MOVEMENT.NONE : INF,
		UNIT_MOVEMENT.FEET : 1.0,
		UNIT_MOVEMENT.WHEELED : 1.0,
		UNIT_MOVEMENT.TRACKED : 1.0,
		UNIT_MOVEMENT.WINGS : 1.0,
		UNIT_MOVEMENT.SHALLOWWATER : INF,
		UNIT_MOVEMENT.DEEPWATER : INF,
		"grounddefense" : 0.1,
		"airdefense" : 0,
		"seadefense" : 0.1,
		"damagetoground" : 0,
		"damagetoair" : 0,
		"damagetosea" : 0,
	},
	BUILDING.SEACONTROL : {
		"name": "Sea Control",
		"description": "Sea Controls enable sea unit manufacturing at your sea-bordering warfactories.",
		"traits": [TERRAIN_TRAIT.GROUND,TERRAIN_TRAIT.CAPTURABLE,TERRAIN_TRAIT.SEAPROFICIENCY,TERRAIN_TRAIT.COVER],
		"sprite" : load("res://sprites/building/395_seacontrol_seacontrol.png"),
		UNIT_MOVEMENT.NONE : INF,
		UNIT_MOVEMENT.FEET : 1.0,
		UNIT_MOVEMENT.WHEELED : 1.0,
		UNIT_MOVEMENT.TRACKED : 1.0,
		UNIT_MOVEMENT.WINGS : 1.0,
		UNIT_MOVEMENT.SHALLOWWATER : INF,
		UNIT_MOVEMENT.DEEPWATER : INF,
		"grounddefense" : 0.1,
		"airdefense" : 0,
		"seadefense" : 0.1,
		"damagetoground" : 0,
		"damagetoair" : 0,
		"damagetosea" : 0,
	},
	BUILDING.FACTORY : {
		"name": "Factory",
		"description": "Warfactories allow you to build new units.",
		"traits": [TERRAIN_TRAIT.SHORE,TERRAIN_TRAIT.CAPTURABLE,TERRAIN_TRAIT.CONSTRUCTION,TERRAIN_TRAIT.COVER],
		"sprite" : load("res://sprites/building/173_factory_factory.png"),
		UNIT_MOVEMENT.NONE : INF,
		UNIT_MOVEMENT.FEET : 1.0,
		UNIT_MOVEMENT.WHEELED : 1.0,
		UNIT_MOVEMENT.TRACKED : 1.0,
		UNIT_MOVEMENT.WINGS : 1.0,
		UNIT_MOVEMENT.SHALLOWWATER : 1.0,
		UNIT_MOVEMENT.DEEPWATER : 1.0,
		"grounddefense" : 0.1,
		"airdefense" : 0,
		"seadefense" : 0.1,
		"damagetoground" : 0,
		"damagetoair" : 0,
		"damagetosea" : 0,
	},
	BUILDING.OILREFINERY : {
		"name": "Oil Refinery",
		"description": "The most basic oil producing property. Capture it to establish an income stream.",
		"traits": [TERRAIN_TRAIT.GROUND,TERRAIN_TRAIT.CAPTURABLE,TERRAIN_TRAIT.LEVEL1OILREFINING,TERRAIN_TRAIT.COVER],
		"sprite" : load("res://sprites/building/180_oilrefinery_oilrefinery.png"),
		UNIT_MOVEMENT.NONE : INF,
		UNIT_MOVEMENT.FEET : 1.0,
		UNIT_MOVEMENT.WHEELED : 1.0,
		UNIT_MOVEMENT.TRACKED : 1.0,
		UNIT_MOVEMENT.WINGS : 1.0,
		UNIT_MOVEMENT.SHALLOWWATER : INF,
		UNIT_MOVEMENT.DEEPWATER : INF,
		"grounddefense" : 0.1,
		"airdefense" : 0,
		"seadefense" : 0.1,
		"damagetoground" : 0,
		"damagetoair" : 0,
		"damagetosea" : 0,
	},
	BUILDING.ADVANCEDOILREFINERY : {
		"name": "Advanced Oil Refinery",
		"description": "An advanced oil production facility. Capture it to enhance your income stream.",
		"traits": [TERRAIN_TRAIT.GROUND,TERRAIN_TRAIT.CAPTURABLE,TERRAIN_TRAIT.LEVEL2OILREFINING,TERRAIN_TRAIT.COVER],
		"sprite" : load("res://sprites/building/370_oiladvanced_oiladvanced.png"),
		UNIT_MOVEMENT.NONE : INF,
		UNIT_MOVEMENT.FEET : 1.0,
		UNIT_MOVEMENT.WHEELED : 1.0,
		UNIT_MOVEMENT.TRACKED : 1.0,
		UNIT_MOVEMENT.WINGS : 1.0,
		UNIT_MOVEMENT.SHALLOWWATER : INF,
		UNIT_MOVEMENT.DEEPWATER : INF,
		"grounddefense" : 0.1,
		"airdefense" : 0,
		"seadefense" : 0.1,
		"damagetoground" : 0,
		"damagetoair" : 0,
		"damagetosea" : 0,
	},
	BUILDING.OILRIG : {
		"name": "Oil Rig",
		"description": "An advanced oil production sea-facility. Capture it with Intrepids to enhance your income stream.",
		"traits": [TERRAIN_TRAIT.GROUND,TERRAIN_TRAIT.CAPTURABLE,TERRAIN_TRAIT.LEVEL2OILREFINING,TERRAIN_TRAIT.COVER],
		"sprite" : load("res://sprites/building/394_oilrig_oilrig.png"),
		UNIT_MOVEMENT.NONE : INF,
		UNIT_MOVEMENT.FEET : 1.0,
		UNIT_MOVEMENT.WHEELED : 1.0,
		UNIT_MOVEMENT.TRACKED : 1.0,
		UNIT_MOVEMENT.WINGS : 1.0,
		UNIT_MOVEMENT.SHALLOWWATER : INF,
		UNIT_MOVEMENT.DEEPWATER : INF,
		"grounddefense" : 0.1,
		"airdefense" : 0,
		"seadefense" : 0.1,
		"damagetoground" : 0,
		"damagetoair" : 0,
		"damagetosea" : 0,
	},
}

var ALBATROSSTRANSPORT_LIST = [
	UNIT.HEAVYCOMMANDO,UNIT.STRIKECOMMANDO,
]

var LEVIATHANBARGE_LIST = [
	UNIT.ANNIHILATORTANK,UNIT.WARMACHINE,UNIT.JAMMERTRUCK,UNIT.LANCERTANK,
	UNIT.SPIDERTANK,UNIT.HEAVYCOMMANDO,UNIT.STRIKECOMMANDO,UNIT.FLAKTANK,
	UNIT.SCORPIONTANK,UNIT.MORTARTRUCK,UNIT.ROCKETTRUCK,UNIT.STEALTHTANK,
	
]



var naturecolor = [
	Color(0.694, 0.678, 0.482),
	Color(0.933, 0.882, 0.612),
	Color(0.694, 0.678, 0.482),
	Color(0.502, 0.4, 0.408),
	Color(0.267, 0.337, 0.255),
	]

var COLOR_RED = [
	Color8(255,000,000),
	Color8(102,026,094),
	Color8(170,022,044),
	Color8(233,051,046),
	Color8(255,144,133),
]

var COLOR_BLUE = [
	Color8(000,000,255),
	Color8(061,049,127),
	Color8(043,095,199),
	Color8(069,164,225),
	Color8(169,207,255),
]

var COLOR_GREEN = [
	Color8(000,255,000),
	Color8(030,091,035),
	Color8(095,147,095),
	Color8(143,222,101),
	Color8(241,246,095),
]

var COLOR_YELLOW = [
	Color8(255,216,000),
	Color8(134,114,052),
	Color8(217,164,073),
	Color8(242,225,104),
	Color8(255,255,160),
]

var COLOR_MAROON = [
	Color8(128,000,000),
	Color8(042,033,052),
	Color8(078,012,035),
	Color8(138,026,017),
	Color8(220,086,086),
]

var COLOR_DK_BLUE = [
	Color8(000,000,139),
	Color8(030,028,059),
	Color8(022,039,117),
	Color8(065,068,147),
	Color8(099,112,173),
]

var COLOR_BROWN = [
	Color8(152,118,084),
	Color8(050,042,050),
	Color8(095,069,104),
	Color8(150,125,041),
	Color8(216,147,069),
]

var COLOR_OLIVE = [
	Color8(128,128,000),
	Color8(053,061,025),
	Color8(065,091,013),
	Color8(130,156,039),
	Color8(203,212,068),
]

var COLOR_ORANGE = [
	Color8(255,165,000),
	Color8(095,056,065),
	Color8(199,065,052),
	Color8(255,182,014),
	Color8(255,255,069),
]

var COLOR_TEAL = [
	Color8(000,128,128),
	Color8(095,086,151),
	Color8(069,147,099),
	Color8(151,216,238),
	Color8(220,255,203),
]

var COLOR_PINK = [
	Color8(255,143,182),
	Color8(114,036,082),
	Color8(196,084,129),
	Color8(255,143,182),
	Color8(255,215,220),
]

var COLOR_WHITE = [
	Color8(245,245,255),
	Color8(106,103,141),
	Color8(179,193,220),
	Color8(229,232,255),
	Color8(245,245,255),
]

var COLOR_VIOLET = [
	Color8(086,069,160),
	Color8(039,043,049),
	Color8(086,069,160),
	Color8(147,130,225),
	Color8(203,194,255),
]

var COLOR_BLACK = [
	Color8(066,065,068),
	Color8(028,029,039),
	Color8(040,044,050),
	Color8(066,065,068),
	Color8(071,075,136),
]

var COLOR_GRAY = [
	Color8(155,151,151),
	Color8(043,049,052),
	Color8(066,078,091),
	Color8(155,151,151),
	Color8(200,190,163),
]

var COLOR_UNFINISHED = [
	Color8(197,171,159),
	Color8(105,125,108),
	Color8(197,171,159),
	Color8(232,223,192),
	Color8(255,255,255),
]

var COLOR_BUILDING = [
	Color8(238,225,156),
	Color8(068,086,065),
	Color8(128,102,104),
	Color8(177,173,123),
	Color8(238,225,156),
]

var COLOR_COIN_GOLD = [
	Color8(238,255,156),
	Color8(150,078,056),
	Color8(229,194,052),
	Color8(255,233,117),
	Color8(255,255,220),
]

var COLOR_COIN_GRAY = [
	Color8(035,059,084),
	Color8(035,059,084),
	Color8(095,111,101),
	Color8(125,153,138),
	Color8(173,183,170),
]






